import Clutter from 'gi://Clutter';
import St from 'gi://St';
const probe = (label, fn) => { try { print(`${label}: ${fn() ? 'OK' : 'MISSING'}`); } catch (e) { print(`${label}: THROWS`); } };
for (const g of ['PanAction', 'TapAction', 'ZoomAction', 'RotateAction', 'SwipeAction', 'DragAction', 'ClickGesture', 'ScrollActor']) probe('Clutter.' + g, () => Clutter[g]);
probe('St.Bin set_content', () => typeof St.Bin.prototype.set_content);
probe('St.Widget set_content', () => typeof St.Widget.prototype.set_content);
probe('St.ImageContent.new_with_preferred_size', () => typeof St.ImageContent.new_with_preferred_size);
probe('St.ImageContent.set_pixbuf', () => typeof St.ImageContent.prototype.set_pixbuf);
probe('St.ImageContent.set_file', () => typeof St.ImageContent.prototype.set_file);
probe('St.ImageContent.set_data', () => typeof St.ImageContent.prototype.set_data);
probe('St.ImageContent.clear', () => typeof St.ImageContent.prototype.clear);
probe('St.BoxLayout spacing prop', () => 'spacing' in St.BoxLayout.prototype);
probe('St.Widget add_style_pseudo_class', () => typeof St.Widget.prototype.add_style_pseudo_class);
probe('St.Widget set_style', () => typeof St.Widget.prototype.set_style);
probe('Clutter.GestureAction.get_last_event', () => typeof Clutter.GestureAction.prototype.get_last_event);
probe('Clutter.Actor.ease_property', () => typeof Clutter.Actor.prototype.ease_property);
probe('St.Label clutter_text', () => true);
probe('St.Entry text prop', () => 'text' in St.Entry.prototype);
probe('St.Viewport child prop', () => 'child' in St.Viewport.prototype);
probe('St.ScrollView overlay_scrollbars', () => 'overlay_scrollbars' in St.ScrollView.prototype);
